FROM node:18-alpine3.17 AS build
WORKDIR /app
COPY ./frontend /app
RUN npm install
RUN npm run build

FROM nginx:alpine AS prod
COPY ./nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["nginx", "-g", "daemon off;"]