version: '3.3'
services:
  openvidu:
    ports:
      - '5443:5443'
    image: 'openvidu/openvidu-dev:2.28.0'
    env_file:
      - ./config/dev/openvidu.env

  rustpad:
    image: ekzhang/rustpad
    ports:
      - '8082:8082'
    environment:
      - PORT=8082

  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    command: uvicorn backend.src.app.app:app --host 0.0.0.0 --port 8080
    ports:
      - '8080:8080'
    links:
      - "openvidu:openvidu"
    env_file:
      - ./config/dev/core.env

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - '80:80'
      - '443:443'